
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const AuthPage = lazy(() => import("./pages/AuthPage.tsx"));
const BiometricLogPage = lazy(() => import("./pages/BiometricLogPage.tsx"));
const ChatPage = lazy(() => import("./pages/ChatPage.tsx"));
const ContentItemPage = lazy(() => import("./pages/ContentItemPage.tsx"));
const DailyCheckinPage = lazy(() => import("./pages/DailyCheckinPage.tsx"));
const DashboardPage = lazy(() => import("./pages/DashboardPage.tsx"));
const NutritionLogPage = lazy(() => import("./pages/NutritionLogPage.tsx"));
const ResourceLibraryPage = lazy(() => import("./pages/ResourceLibraryPage.tsx"));
const SettingsPage = lazy(() => import("./pages/SettingsPage.tsx"));
const SignUpPage = lazy(() => import("./pages/SignUpPage.tsx"));
const TrainingLogPage = lazy(() => import("./pages/TrainingLogPage.tsx"));
const WellnessLogPage = lazy(() => import("./pages/WellnessLogPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/auth-page", element: <AuthPage />},
	{ path: "/authpage", element: <AuthPage />},
	{ path: "/biometric-log-page", element: <BiometricLogPage />},
	{ path: "/biometriclogpage", element: <BiometricLogPage />},
	{ path: "/chat-page", element: <ChatPage />},
	{ path: "/chatpage", element: <ChatPage />},
	{ path: "/content-item-page", element: <ContentItemPage />},
	{ path: "/contentitempage", element: <ContentItemPage />},
	{ path: "/daily-checkin-page", element: <DailyCheckinPage />},
	{ path: "/dailycheckinpage", element: <DailyCheckinPage />},
	{ path: "/dashboard-page", element: <DashboardPage />},
	{ path: "/dashboardpage", element: <DashboardPage />},
	{ path: "/nutrition-log-page", element: <NutritionLogPage />},
	{ path: "/nutritionlogpage", element: <NutritionLogPage />},
	{ path: "/resource-library-page", element: <ResourceLibraryPage />},
	{ path: "/resourcelibrarypage", element: <ResourceLibraryPage />},
	{ path: "/settings-page", element: <SettingsPage />},
	{ path: "/settingspage", element: <SettingsPage />},
	{ path: "/sign-up-page", element: <SignUpPage />},
	{ path: "/signuppage", element: <SignUpPage />},
	{ path: "/training-log-page", element: <TrainingLogPage />},
	{ path: "/traininglogpage", element: <TrainingLogPage />},
	{ path: "/wellness-log-page", element: <WellnessLogPage />},
	{ path: "/wellnesslogpage", element: <WellnessLogPage />},

];
