
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router";
import RouteErrorElement from "./components/RouteErrorElement";

import App from "./pages/App";
import AuthPage from "./pages/AuthPage";
import BiometricLogPage from "./pages/BiometricLogPage";
import ChatPage from "./pages/ChatPage";
import ContentItemPage from "./pages/ContentItemPage";
import DailyCheckinPage from "./pages/DailyCheckinPage";
import DashboardPage from "./pages/DashboardPage";
import NutritionLogPage from "./pages/NutritionLogPage";
import ResourceLibraryPage from "./pages/ResourceLibraryPage";
import SettingsPage from "./pages/SettingsPage";
import SignUpPage from "./pages/SignUpPage";
import TrainingLogPage from "./pages/TrainingLogPage";
import WellnessLogPage from "./pages/WellnessLogPage";

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />, errorElement: <RouteErrorElement /> },
	{ path: "/auth-page", element: <AuthPage />, errorElement: <RouteErrorElement /> },
	{ path: "/authpage", element: <AuthPage />, errorElement: <RouteErrorElement /> },
	{ path: "/biometric-log-page", element: <BiometricLogPage />, errorElement: <RouteErrorElement /> },
	{ path: "/biometriclogpage", element: <BiometricLogPage />, errorElement: <RouteErrorElement /> },
	{ path: "/chat-page", element: <ChatPage />, errorElement: <RouteErrorElement /> },
	{ path: "/chatpage", element: <ChatPage />, errorElement: <RouteErrorElement /> },
	{ path: "/content-item-page", element: <ContentItemPage />, errorElement: <RouteErrorElement /> },
	{ path: "/contentitempage", element: <ContentItemPage />, errorElement: <RouteErrorElement /> },
	{ path: "/daily-checkin-page", element: <DailyCheckinPage />, errorElement: <RouteErrorElement /> },
	{ path: "/dailycheckinpage", element: <DailyCheckinPage />, errorElement: <RouteErrorElement /> },
	{ path: "/dashboard-page", element: <DashboardPage />, errorElement: <RouteErrorElement /> },
	{ path: "/dashboardpage", element: <DashboardPage />, errorElement: <RouteErrorElement /> },
	{ path: "/nutrition-log-page", element: <NutritionLogPage />, errorElement: <RouteErrorElement /> },
	{ path: "/nutritionlogpage", element: <NutritionLogPage />, errorElement: <RouteErrorElement /> },
	{ path: "/resource-library-page", element: <ResourceLibraryPage />, errorElement: <RouteErrorElement /> },
	{ path: "/resourcelibrarypage", element: <ResourceLibraryPage />, errorElement: <RouteErrorElement /> },
	{ path: "/settings-page", element: <SettingsPage />, errorElement: <RouteErrorElement /> },
	{ path: "/settingspage", element: <SettingsPage />, errorElement: <RouteErrorElement /> },
	{ path: "/sign-up-page", element: <SignUpPage />, errorElement: <RouteErrorElement /> },
	{ path: "/signuppage", element: <SignUpPage />, errorElement: <RouteErrorElement /> },
	{ path: "/training-log-page", element: <TrainingLogPage />, errorElement: <RouteErrorElement /> },
	{ path: "/traininglogpage", element: <TrainingLogPage />, errorElement: <RouteErrorElement /> },
	{ path: "/wellness-log-page", element: <WellnessLogPage />, errorElement: <RouteErrorElement /> },
	{ path: "/wellnesslogpage", element: <WellnessLogPage />, errorElement: <RouteErrorElement /> },

];
